PREFIX ehr: <http://www.semanticweb.org/redwanwalid/ontologies/2022/1/untitled-ontology-99#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xml: <http://www.w3.org/XML/1998/namespace>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT DISTINCT ?individual
WHERE {
?individual rdf:type owl:NamedIndividual .
}